name: flux_theme_playground
description: A Very Good Project created by Very Good CLI.
version: 0.0.1+6
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  bloc:

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  flux_lints:
    path: ../../packages_dev/flux_lints

flutter:
  uses-material-design: true
  generate: true
