name: flux_theme_playground
description: A Very Good Project created by Very Good CLI.
version: 0.0.1+2
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.1

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  flux_lints:
    path: ../flux_lints
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
