name: firebase_provider
description: A new Flutter package project.
version: 0.0.1

homepage: "#"

publish_to: "none"

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  # firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  cloud_firestore: ^2.2.0
  flutter:
    sdk: flutter
  # google_sign_in: ^5.0.3
  logging: ^1.0.1
  riverpod: ^1.0.0-dev.6
  flutter_riverpod: ^1.0.0-dev.6
  # flutter_facebook_auth: ^3.4.0
  # firebase_messaging: ^10.0.2
  # flutter_local_notifications: ^6.0.0
  # firebase_crashlytics: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
