name: flux_widgets_dev
description: A Very Good Project created by Very Good CLI.
version: 0.1.3+2
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  spaces: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flux_lints:
    path: ../../packages_dev/flux_lints
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
