name: flux_widgets_dev
description: A Very Good Project created by Very Good CLI.
version: 0.1.3+2
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  flux_widgets:
    path: ../../packages/flux_widgets

dependency_overrides:
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flux_lints:
    path: ../../packages_dev/flux_lints

flutter:
  uses-material-design: true
