arb-dir: lib/l10n/arb
template-arb-file: app_en.arb
output-localization-file: app_intl.dart
output-class: AppIntl
nullable-getter: false

preferred-supported-locales:
  - en
use-deferred-loading: true
