name: flux_api_config
description: A Very Good Project created by Very Good CLI.
version: 0.1.1+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  openapi_generator_annotations: ^4.0.0

dev_dependencies:
  build_runner:
  flux_lints:
  mocktail: ^0.3.0
  openapi_generator: ^4.0.0
  test: ^1.19.2
