name: auth_signup
description: A new Flutter package project.
version: 0.0.2+2
homepage: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flux_lints:
    path: ../../packages_dev/flux_lints