name: flux
description: A Very Good Project created by Very Good CLI.
version: 0.1.2
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flux_theme:
    path: ../../packages/flux_theme
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flux_lints:
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
