name: flux_intl
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+2
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flux_lints:
  mocktail: ^0.3.0
