name: flux_riverpod
description: A new Flutter package project.
version: 0.0.1

publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.3.0
  hooks_riverpod: ^2.3.0

  riverpod_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  riverpod_generator: ^2.0.0

  flux_lints:
    path: ../../packages_dev/flux_lints

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
