name: flux_theme
description: A Very Good Project created by Very Good CLI.
version: 0.0.1+4
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.1

dependencies:
  flex_color_scheme: ^6.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flux_lints:
    path: ../flux_lints

flutter:
  uses-material-design: true
