name: flux_theme
description: A Very Good Project created by Very Good CLI.
version: 0.0.1+7
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flex_color_scheme: ^6.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flux_lints:
    path: ../../packages_dev/flux_lints

flutter:
  uses-material-design: true
