name: flux_navigation
description: A Very Good Project created by Very Good CLI.
version: 0.1.2+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flux_lints:
  go_router_builder: ^1.0.14
  mocktail: ^0.3.0
