name: flux_navigation
description: A Very Good Project created by Very Good CLI.
version: 0.1.2+2
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flux_lints:
    path: ../../packages_dev/flux_lints
  go_router_builder: ^1.1.6
