
include: package:flux_lints/riverpod.yaml

analyzer:
  exclude:
    - "**/.vscode/*"
    - "**/bricks/**/*"
    - "**/__brick__"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
    - "**/*.gen.dart"
    - "**/generated_plugin_registrant.dart"
    - "**/dart_env.dart"