name: flux_r13n
description: A package that enables region-specific configurations (regionalization). Built by Very Good Ventures.
version: 0.1.0-dev.3
homepage: https://github.com/VeryGoodOpenSource/flux_r13n
repository: https://github.com/VeryGoodOpenSource/flux_r13n
issue_tracker: https://github.com/VeryGoodOpenSource/flux_r13n/issues

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flux_lints:
    path: ../flux_lints
