openapi: 3.0.0
servers:
  - url: https://{environment}.newapp.com.vn
    variables:
      environment:
        default: api # Production server
        enum:
          - api # Production server
          - api-dev # Development server
          - api-qa # Testing server
info:
  description: >-
    This is a sample server Petstore server. For this sample, you can use the api key
    `special-key` to test the authorization filters.
  version: 1.0.0
  title: OpenAPI Petstore
  license:
    name: Apache-2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"

paths:
  # Auth
  /identity/auth/status:
    $ref: ./resources/Auth/Login.yaml
  /connect/token:
    $ref: ./resources/Auth/LoginFormEncoded.yaml
  /identity/auth/login/oauth2:
    $ref: ./resources/Auth/LoginWithSocialAccount.yaml
  /identity/authenticated/auth/logout:
    $ref: ./resources/Auth/Logout.yaml
  /identity/auth/register:
    $ref: ./resources/Auth/Register.yaml
  /identity/account/verify:
    $ref: ./resources/Auth/VerifyOTP.yaml
  /identity/account/password/forgot:
    $ref: ./resources/Auth/ForgotPassword.yaml
  /identity/account/password/check-recovery-code:
    $ref: ./resources/Auth/VerifyForgotPasswordCode.yaml
  /identity/account/password/set-new-password:
    $ref: ./resources/Auth/ChangePassword.yaml
  /identity/account/resend-verify-code:
    $ref: ./resources/Auth/ResendOTP.yaml
  /identity/auth/refresh-token:
    $ref: ./resources/Auth/RefreshToken.yaml
  /users/users/profile/me:
    $ref: ./resources/Auth/UserInfo.yaml
  /identity/authenticated/auth/change-password:
    $ref: ./resources/Auth/ProfileChangePassword.yaml
  /users/users/profile:
    $ref: ./resources/Auth/UpdateProfile.yaml
  /users/users/settings:
    $ref: ./resources/Auth/UpdatePNSetting.yaml

  # Payment
  /payment/transactions/me:
    $ref: ./resources/Payment/TransactionHistories.yaml
  /payment/tickets:
    $ref: ./resources/Payment/sendNonce.yaml
  /payment/tokens/braintree:
    $ref: ./resources/Payment/clientToken.yaml

  # Notification
  /notification/notification/register-device:
    $ref: ./resources/Notification/RegisterDevice.yaml

components:
  schemas:
    AuthenError-ref:
      $ref: ./components/schemas/ErrorDetails.yaml#/AuthenError
    AppUpdateStatus-ref:
      $ref: ./components/schemas/AppUpdateStatus.yaml
    CommentModel-ref:
      $ref: ./components/schemas/CommentModel.yaml
    EmailCredentials-ref:
      $ref: ./components/schemas/EmailCredentials.yaml
    ErrorCode-ref:
      $ref: ./components/schemas/ErrorCode.yaml
    ErrorResponse-ref:
      $ref: ./components/schemas/ErrorResponse.yaml
    ExpandingState-ref:
      $ref: ./components/schemas/ExpandingState.yaml
    ExternalProvider-ref:
      $ref: ./components/schemas/ExternalProvider.yaml
    FBSRemoteConfigs-ref:
      $ref: ./components/schemas/FBSRemoteConfigs.yaml
    # FCMRemoteMessage-ref:
    #   $ref: ./components/schemas/FCMRemoteMessage.yaml
    FSLabel-ref:
      $ref: ./components/schemas/FSLabel.yaml
    LoadingState-ref:
      $ref: ./components/schemas/LoadingState.yaml
    MobileCredentials-ref:
      $ref: ./components/schemas/MobileCredentials.yaml
    NotificationName-ref:
      $ref: ./components/schemas/NotificationName.yaml
    NetworkStateResult-ref:
      $ref: ./components/schemas/NetworkState.yaml#/NetworkStateResult
    PlatformParameter-ref:
      $ref: ./components/schemas/PlatformParameter.yaml
    ProviderType-ref:
      $ref: ./components/schemas/ProviderType.yaml
    StatusCode-ref:
      $ref: ./components/schemas/StatusCode.yaml
    TransactionModel-ref:
      $ref: ./components/schemas/TransactionModel.yaml
    User-ref:
      $ref: ./components/schemas/User.yaml
    UserState-ref:
      $ref: ./components/schemas/UserState.yaml
    PaymentError-ref:
      $ref: ./components/schemas/ErrorDetails.yaml#/PaymentError
    PaypalParameter-ref:
      $ref: ./components/requestBody/PaypalParameter.yaml
    MoMoParameters-ref:
      $ref: ./components/requestBody/MoMoParameters.yaml
    CommentState-ref:
      $ref: ./components/schemas/CommentState.yaml
    PostEmotion-ref:
      $ref: ./components/requestBody/PostEmotion.yaml

  securitySchemes:
    bearerAuth:
      $ref: ./components/securitySchemes/BearerAuth.yaml
