
analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    implicit-dynamic: false
    implicit-casts: false
  exclude:
    - test/*.dart
  errors:
    unused_import: ignore

linter:
  rules:
    