name: permission_att
description: A new Flutter package project.
version: 0.0.2+1

homepage: none

publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission:
    path: ../../core/permission

dev_dependencies:
  flutter_test:
    sdk: flutter
  flux_lints:
    path: ../../packages_dev/flux_lints
