name: flux

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel:
          # - dev
          - stable

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.5.0
        with:
          flutter-version: '2.2.1'
          # channel: ${{ matrix.channel }}

      - name: Install global packages
        run: |
          dart pub global activate melos

      - name: Add pub cache bin to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Add pub cache to PATH
        run: echo "PUB_CACHE="$HOME/.pub-cache"" >> $GITHUB_ENV

      - name: Install dependencies
        run: melos bootstrap

      - name: Format
        run: melos run format

      - name: Analyze
        run: melos run analyze

      - name: Run tests
        run: melos run test

      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash | bash
